### PR TITLE
Query to Stream to match latest Fable.Elmish.Reaction

### PR DESCRIPTION
**Pull request by dbrattli**
Does this look better?

### CODE REVIEW

**Comment by rommsen** [comment]
Looks much better and with the asStream operator even cleaner imo. Could you also rename Magic.query and Info.query?

**Comment by dbrattli** [comment]
Yes, can do that. Just discovered that the Playground does not work in production mode i.e `-p`. Debugging ...

**Comment by dbrattli** [comment]
Bug is btw with JS minify plugin terser. We need to disable inlining of functions in webpack config. I'll add it.

**Comment by rommsen** [comment]
Thanks @dbrattli really cool

**Comment by dbrattli** [comment]
Thanks @rommsen . Think the code looks much better now. But somehow I wish that we could have given a stream as input as well as output i.e `(msgs: Stream<Msg, string>)` instead of `IAsyncObservable<Msg>`. Not sure how to do it and make it look nice. You want to use the stream directly without going through `AsyncRx.ofStream` or similar to turn it into an `IAsyncObservable` in order to compose the operators. A Stream should also implement `IAsyncObservable`, something like
```fs
and Stream<'msg, 'name> =
    /// Named message stream
    | Stream of IAsyncObservable<'msg>*'name
    /// Collection of named streams
    | Streams of Stream<'msg,'name> list
    /// Dispose message stream
    | Dispose
    interface IAsyncObservable<'msg> with
        member this.SubscribeAsync obv =
            async {
                // TODO:
                return AsyncDisposable.Empty
            } 
```

**Comment by rommsen** [comment]
@dbrattli this would be pretty cool because then we could lift ourselves completely from IAsyncObservable (in elmish) and do not need to juggle between different concepts

**Comment by dbrattli** [comment]
@rommsen This first try actually works for the Stream case. Need to figure out what to do with the Streams list case. 
```fs
and Stream<'msg, 'name> =
    /// Named message stream
    | Stream of IAsyncObservable<'msg>*'name
    /// Collection of named streams
    | Streams of Stream<'msg,'name> list
    /// Dispose message stream
    | Dispose
    interface IAsyncObservable<'msg> with
        member this.SubscribeAsync obv =
            async {
                match this with
                | Stream (xs, name) ->
                    return! xs.SubscribeAsync obv
                | Streams xss -> ???
                | _ ->
                    return AsyncDisposable.Empty
            }
```

**Comment by rommsen** [comment]
@dbrattli why cant we just call `this.SubscribeAsync obv` recursively for each list item?

**Comment by rommsen** [comment]
a forget it, we need to return one async in the end

**Comment by dbrattli** [comment]
Not a problem, we just make a `compositDisposable`. Basically just merging all the streams. I will fix it later today.

**Comment by rommsen** [comment]
Great

**Comment by dbrattli** [comment]
Something like this should work:

```fs
type Stream<'msg, 'name> =
    /// Named message stream
    | Stream of IAsyncObservable<'msg>*'name
    /// Collection of named streams
    | Streams of Stream<'msg, 'name> list
    /// Dispose message stream
    | Dispose
    interface IAsyncObservable<'msg> with
        member this.SubscribeAsync obv =
            let rec flatten streams =
                [
                    for stream in streams do
                        match stream with
                        | Stream (xs, _) ->
                            yield xs
                        | Streams xss ->
                            yield! flatten xss
                        | _ -> ()
                ]
            async {
                match this with
                | Stream (xs, _) ->
                    return! xs.SubscribeAsync obv
                | Streams xss ->
                    let xs = flatten xss |> AsyncRx.mergeSeq
                    return! xs.SubscribeAsync obv
                | _ ->
                    return AsyncDisposable.Empty
            }
```

**Comment by rommsen** [comment]
@dbrattli: Correct me if I am wrong but wasnt the goal with multiple Streams to have independent streams that we can dispose independently? When we do something like 
```F#
| Streams xss ->
    let xs = flatten xss |> AsyncRx.mergeSeq
    return! xs.SubscribeAsync obv
```

Dont we loose this behaviour?

**Comment by dbrattli** [comment]
I don't think so since Observables are immutable in the sense that:

```fs
let xs = AsyncRx.interval 1000 1000

let ys = xs |> AsyncRx.map (fun x -> x * 10)
let zs = ys |> AsyncRx.map (fun x -> x * 100)

let! sub1 = ys.SubscribeAsync obv1
let! sub2 = zs.SubscribeAsync obv2
...
do! sub1.DisposeAsync ()
// This has nothing to do with sub2
```
So you can give `sub1` a name, subscribe it and dispose it. It has nothing to do with `sub2`. They live their separate lives. Thus in the code above, when you have both subscriptions, then the first `map` will be called twice for every value (since there are 2 subscriptions). 

That said, it's probably not the case that you need all the streams down into a sub-component, so we can make a function that picks a stream with a given name and ignores the rest, so you don't end up with multiple websockets connections etc etc.

**Comment by rommsen** [comment]
ok thanks for the heads up

**Pull request merged**
